import asyncio
import socket
import logging
import threading
import httpx
import json
from datetime import datetime

import paramiko

# Add parent dir to path if run standalone
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config import settings

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("ssh_honeypot")

# Fast API honeypot endpoint
FASTAPI_TRAP_URL = f"http://localhost:{settings.PORT}/trap/execute"

class HoneypotInterface(paramiko.ServerInterface):
    """
    Paramiko ServerInterface to handle SSH authentication attempts.
    We accept ANY username/password combination to lure the attacker in.
    """
    def __init__(self, client_ip):
        self.client_ip = client_ip
        self.event = threading.Event()

    def check_channel_request(self, kind, chanid):
        if kind == 'session':
            return paramiko.OPEN_SUCCEEDED
        return paramiko.OPEN_FAILED_ADMINISTRATIVELY_PROHIBITED

    def check_auth_password(self, username, password):
        """
        Intercept the brute-forced credentials and log them.
        Accepts all credentials to allow the attacker into the honeypot shell.
        """
        logger.warning(f"🚨 [SSH Auth Attempt] IP: {self.client_ip} | User: {username} | Pass: {password}")
        
        # We can asynchronously log this to our backend as a specific "brute_force" attack if we wanted,
        # but for now, we just let them in to capture their actual commands.
        
        # Always return Auth Successful to lure them in
        return paramiko.AUTH_SUCCESSFUL

    def check_channel_pty_request(self, channel, term, width, height, pixelwidth, pixelheight, modes):
        return True

    def check_channel_shell_request(self, channel):
        self.event.set()
        return True

    def get_allowed_auths(self, username):
        return 'password'


async def forward_command_to_brain(ip_address: str, command: str) -> str:
    """
    Forwards the raw shell command to the central FastAPI /trap/execute endpoint.
    Returns the deceptive output generated by the BiLSTM/LLM.
    """
    payload = {
        "command": command,
        "ip_address": ip_address
    }
    
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(FASTAPI_TRAP_URL, json=payload)
            response.raise_for_status()
            data = response.json()
            return data.get("response", "")
    except httpx.ConnectError:
        logger.error(f"Failed to connect to central brain at {FASTAPI_TRAP_URL}. Is FastAPI running?")
        return "bash: connection closed by remote host\r\n"
    except Exception as e:
        logger.error(f"Error forwarding command to brain: {e}")
        return "bash: internal error\r\n"


def handle_connection(client_socket, client_address):
    """
    Handles an individual incoming SSH connection.
    """
    client_ip = client_address[0]
    logger.info(f"Incoming connection from {client_ip}:{client_address[1]}")
    
    try:
        transport = paramiko.Transport(client_socket)
        
        # Load a host key. You normally generate one with:
        # ssh-keygen -t rsa -f server_rsa.key
        key_path = os.path.join(os.path.dirname(__file__), 'server_rsa.key')
        
        # Generate on the fly if it doesn't exist for easy setup
        if not os.path.exists(key_path):
            logger.info("Generating new RSA host key...")
            key = paramiko.RSAKey.generate(2048)
            key.write_private_key_file(key_path)
            
        host_key = paramiko.RSAKey(filename=key_path)
        transport.add_server_key(host_key)
        
        server = HoneypotInterface(client_ip)
        
        try:
            transport.start_server(server=server)
        except paramiko.SSHException as e:
            logger.error(f"SSH negotiation failed: {e}")
            return

        # Wait for authentication
        channel = transport.accept(20)
        if channel is None:
            logger.info(f"No channel created for {client_ip}.")
            return
            
        server.event.wait(10)
        if not server.event.is_set():
            logger.info(f"Client {client_ip} never requested a shell.")
            return

        logger.info(f"Virtual shell opened for {client_ip}")
        
        # Send initial fake MOTD
        channel.send("Welcome to Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-91-generic x86_64)\r\n\r\n")
        channel.send(" * Documentation:  https://help.ubuntu.com\r\n")
        channel.send(" * Management:     https://landscape.canonical.com\r\n")
        channel.send(" * Support:        https://ubuntu.com/advantage\r\n\r\n")
        channel.send("Last login: Mon Feb 19 14:32:01 2024 from 192.168.1.45\r\n")
        
        # The prompt
        prompt = "root@ubuntu:~# "
        channel.send(prompt)

        # Simple REPL loop for the SSH session
        command_buffer = ""
        client_exit = False
        while not client_exit:
            char_buf = channel.recv(1024).decode('utf-8', errors='ignore')
            if not char_buf:
                break
                
            for char in char_buf:
                # Handle Enter key
                if char in ('\r', '\n'):
                    channel.send('\r\n')
                    cmd = command_buffer.strip()
                    command_buffer = ""
                    
                    if cmd in ["exit", "logout"]:
                        logger.info(f"Client {client_ip} exited the shell.")
                        client_exit = True
                        break
                    
                    if cmd:
                        # Sync to Async bridge to call the FastAPI endpoint
                        logger.info(f"[{client_ip}] Executing: {cmd}")
                        
                        try:
                            loop = asyncio.get_event_loop()
                        except RuntimeError:
                            loop = asyncio.new_event_loop()
                            asyncio.set_event_loop(loop)
                            
                        response_text = loop.run_until_complete(
                            forward_command_to_brain(client_ip, cmd)
                        )
                        
                        # Ensure newlines form properly in the terminal
                        if response_text:
                            response_text = response_text.replace('\n', '\r\n')
                            if not response_text.endswith('\r\n'):
                                response_text += '\r\n'
                            channel.send(response_text)
                    
                    channel.send(prompt)
                    
                # Handle Backspace
                elif char in ('\x08', '\x7f'):
                    if len(command_buffer) > 0:
                        command_buffer = command_buffer[:-1]
                        # Erase character visually from terminal
                        channel.send('\x08 \x08')
                # Handle Ctrl+C (Interrupt)
                elif char == '\x03':
                    channel.send('^C\r\n' + prompt)
                    command_buffer = ""
                # Handle Ctrl+D (EOF)
                elif char == '\x04':
                    if not command_buffer:
                        channel.send("\r\nlogout\r\n")
                        client_exit = True
                        break
                else:
                    # Echo character back and add to buffer
                    channel.send(char)
                    command_buffer += char

    except Exception as e:
        logger.error(f"Connection error with {client_ip}: {e}")
    finally:
        try:
            transport.close()
        except:
            pass

def start_honeypot(host='0.0.0.0', port=2222):
    """
    Main entry point for starting the SSH server socket.
    """
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        sock.bind((host, port))
        sock.listen(100)
        
        logger.info(f"✅ SSH Honeypot listening on {host}:{port}")
        logger.info(f"   Forwarding payloads to {FASTAPI_TRAP_URL}")
        
        while True:
            client_socket, client_addr = sock.accept()
            # Handle each connection in a new thread
            t = threading.Thread(target=handle_connection, args=(client_socket, client_addr))
            t.daemon = True
            t.start()
            
    except Exception as e:
        logger.error(f"Failed to start SSH honeypot: {e}")
    finally:
        sock.close()

if __name__ == "__main__":
    start_honeypot()
